const productList = [
  {
    id: "01",
    img: "https://picsum.photos/901",
    name: "product1",
    normalPrice: 100,
    sellPrice: 80,
    quantity: 0,
  },
  {
    id: "02",
    img: "https://picsum.photos/902",
    name: "product2",
    normalPrice: 100,
    sellPrice: 70,
    quantity: 30,
  },
  {
    id: "03",
    img: "https://picsum.photos/903",
    name: "product3",
    normalPrice: 120,
    sellPrice: 80,
    quantity: 0,
  },
  {
    id: "04",
    img: "https://picsum.photos/904",
    name: "product4",
    normalPrice: 200,
    sellPrice: 150,
    quantity: 30,
  },
  {
    id: "05",
    img: "https://picsum.photos/905",
    name: "product5",
    normalPrice: 100,
    sellPrice: 80,
    quantity: 30,
  },
  {
    id: "06",
    img: "https://picsum.photos/906",
    name: "product6",
    normalPrice: 150,
    sellPrice: 120,
    quantity: 30,
  },
  {
    id: "07",
    img: "https://picsum.photos/907",
    name: "product7",
    normalPrice: 100,
    sellPrice: 80,
    quantity: 30,
  },
  {
    id: "08",
    img: "https://picsum.photos/808",
    name: "product8",
    normalPrice: 100,
    sellPrice: 80,
    quantity: 30,
  },
  {
    id: "09",
    img: "https://picsum.photos/909",
    name: "product9",
    normalPrice: 100,
    sellPrice: 80,
    quantity: 0,
  },
  {
    id: "10",
    img: "https://picsum.photos/910",
    name: "product10",
    normalPrice: 100,
    sellPrice: 80,
    quantity: 30,
  },
  {
    id: "11",
    img: "https://picsum.photos/911",
    name: "product11",
    normalPrice: 300,
    sellPrice: 270,
    quantity: 0,
  },
  {
    id: "12",
    img: "https://picsum.photos/912",
    name: "product12",
    normalPrice: 250,
    sellPrice: 220,
    quantity: 40,
  },
];

export default productList;
